services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ssf_app
      POSTGRES_USER: ssf_user
      POSTGRES_PASSWORD: ssf_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
